# Generate commit history and save to data directory.
name: Commit History

on:
  push:
    branches:
      - master
  pull_request:

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive
          fetch-depth: 0
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.32
      - name: Generate Commit History
        run: |
          rm -f ./data/commit_history.json
          deno run --allow-read --allow-run --allow-write  ./scripts/commit_history.ts
      # Get diff and commit/push if it exists.
      # Referenced from https://zenn.dev/snowcait/articles/903d86d668fcb7.
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'chore: Generate commit history'
          git push
        if: steps.diff.outcome == 'failure'
